# Air-gapped cluster example values
# - No public ingress
# - No DNS or egress to the Internet
# - JWKS served from a mounted Secret file

adminSecretRefName: oscillink-admin-env

env:
  # Use file-based JWKS for zero egress
  OSCILLINK_JWKS_URL: file:///run/secrets/jwks.json
  OSCILLINK_LICENSE_REQUIRED: "1"
  OSCILLINK_METRICS_PROTECTED: "1"

secretMounts:
  - name: license
    mountPath: /run/secrets
    secretName: oscillink-license
    # Secret should contain:
    # - jwks.json      (the JWKS document)
    # - oscillink.lic  (license token if used by entrypoint)

service:
  type: ClusterIP

ingress:
  enabled: false

networkPolicy:
  enabled: true
  allowDNS: false
  # Block all egress by providing an empty ports list and no CIDR destinations
  egressCIDR: 127.0.0.1/32 # dummy unreachable destination
  egressPorts: [1]         # dummy unreachable port to satisfy chart schema

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu:
    enabled: true
    targetAverageUtilization: 70

pdb:
  enabled: true
  minAvailable: 1
