repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Use the newer ruff so config codes are recognized consistently
    rev: v0.12.12
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--fix"]
      - id: ruff-format
        name: ruff (format)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # Keep pre-commit mypy fast and focused (full mypy runs in CI tasks)
        files: ^oscillink/.*\.py$
        additional_dependencies: []

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
        exclude: ^deploy/helm/.*
      - id: check-toml
