name: Bug report
description: Report a problem or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Minimal code snippet or commands to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package Version
      description: Output of `python -c "import oscillink; print(oscillink.__version__)"`
  - type: input
    id: python
    attributes:
      label: Python Version
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Traceback
      render: shell
  - type: textarea
    id: extra
    attributes:
      label: Additional Context
