version: '3.8'
services:
  oscillink:
    # Keep tag in sync with latest release
    image: ghcr.io/oscillink/oscillink:v0.1.13
    ports:
      - "8000:8080"
    environment:
      OSCILLINK_LICENSE_PATH: "/run/secrets/oscillink.lic"
      OSCILLINK_JWKS_URL: "https://license.oscillink.com/.well-known/jwks.json"
      # Optional JWT verification expectations
      # OSCILLINK_JWT_ISS: "https://license.oscillink.com"
      # OSCILLINK_JWT_AUD: "oscillink"
      # OSCILLINK_JWT_LEEWAY: "300"
      # OSCILLINK_JWKS_TTL: "3600"
      # OSCILLINK_JWKS_OFFLINE_GRACE: "86400"
      OSCILLINK_TELEMETRY: "minimal"
      OSCILLINK_USAGE_LOG: "/data/usage.jsonl"
  # --- Stripe billing (optional) ---
  # STRIPE_SECRET_KEY: "sk_live_xxx"
  # STRIPE_WEBHOOK_SECRET: "whsec_xxx"
  # OSCILLINK_STRIPE_PRICE_MAP: ${OSCILLINK_STRIPE_PRICE_MAP:-}
  # OSCILLINK_STRIPE_MAX_AGE: "300"   # max timestamp age for webhook signature
  # OSCILLINK_ALLOW_UNVERIFIED_STRIPE: "0"  # NEVER enable in prod
  # OSCILLINK_CUSTOMERS_COLLECTION: "oscillink_customers"  # enable when using Firestore mapping
  # OSCILLINK_WEBHOOK_EVENTS_COLLECTION: "oscillink_webhooks"  # optional persistence for events
      # Optional: configure flush to your service
      # OSCILLINK_USAGE_FLUSH_URL: "https://license.oscillink.com/v1/usage/report"
      # OSCILLINK_LICENSE_ID: "lic_xxx"
    volumes:
      - type: bind
        source: ./license
        target: /run/secrets
      - type: bind
        source: ./data
        target: /data
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 5s
      start_period: 20s
