{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oscillink.fullname" . }}
  labels:
    app: {{ include "oscillink.name" . }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "oscillink.name" . }}
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    {{- if .Values.networkPolicy.allowDNS }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    - to:
        - ipBlock:
            cidr: {{ default "0.0.0.0/0" .Values.networkPolicy.egressCIDR }}
      ports:
        {{- range $p := .Values.networkPolicy.egressPorts }}
        - protocol: TCP
          port: {{ $p }}
        {{- end }}
{{- end }}
