{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "oscillink.fullname" .) .Values.serviceAccount.name }}
  labels:
    app: {{ include "oscillink.name" . }}
    release: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
