deterministic: true
watch_dir: /data/docs
index_dir: /data/index
receipts_dir: /data/receipts
reports_dir: /data/reports

ocr:
  engine: "tesseract"
  langs: ["eng"]
  enable_if_no_text: true

chunking:
  engine: "unstructured"
  max_tokens: 800
  overlap: 120
  by_title: true

embeddings:
  model: "BAAI/bge-small-en-v1.5"
  dim: 384
  verify_sha256: true

ann:
  backend: "faiss"
  params:
    type: "hnsw"
    M: 32
    efSearch: 64
  top_k: 60

oscillink:
  kneighbors: 6
  lamG: 1.0
  lamC: 0.5
  lamQ: 4.0
  bundle_k: 8
  abstain:
    deltaH_min: 1e-3
    score_min: 0.30

llm:
  mode: "openai_compatible"
  endpoint: "http://127.0.0.1:11434/v1"
  api_key_env: "LOCAL_LLM_KEY"
  model: "my-local-model"
  max_tokens: 600
  temperature: 0.2

ui:
  auth: "local"
