image:
  repository: ghcr.io/oscillink/oscillink
  tag: v0.1.13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "2Gi"

env:
  OSCILLINK_JWKS_URL: https://license.oscillink.com/.well-known/jwks.json
  OSCILLINK_TELEMETRY: minimal
  # Licensed container defaults
  OSCILLINK_LICENSE_PATH: /run/secrets/oscillink.lic
  OSCILLINK_LICENSE_REQUIRED: "1"
  OSCILLINK_ENTITLEMENTS_PATH: /run/oscillink_entitlements.json
  # Protect /metrics with admin secret by default (set OSCILLINK_ADMIN_SECRET via Secret)
  OSCILLINK_METRICS_PROTECTED: "1"

# Optional: reference a Secret that contains sensitive env vars (e.g., OSCILLINK_ADMIN_SECRET)
# The Secret keys will be exposed as envs. Example:
# adminSecretRefName: oscillink-admin-env
adminSecretRefName: ""

secretMounts:
  - name: license
    mountPath: /run/secrets
    secretName: oscillink-license

ingress:
  enabled: false
  host: ""
  className: ""
  annotations: {}
  tls:
    enabled: false
    secretName: ""

networkPolicy:
  enabled: false
  # Allow DNS egress for JWKS lookups if your cluster requires it
  allowDNS: true
  # CIDR for egress (use your egress gateway CIDR or 0.0.0.0/0)
  egressCIDR: 0.0.0.0/0
  # Common ports for HTTPS/HTTP JWKS endpoints
  egressPorts:
    - 443
    - 80

pdb:
  enabled: false
  # One of these can be set
  minAvailable: 1
  # maxUnavailable: 0

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  cpu:
    enabled: true
    targetAverageUtilization: 70
  memory:
    enabled: false
    targetAverageUtilization: 80
